
# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pool:
  vmImage: 'Ubuntu 16.04'

steps:

- task: CmdLine@2
  inputs:
    script:
      echo "Setting up JAVA_HOME..."
      export JAVA_HOME='/usr/aazeen'
      ls -/home/vsts/
      cat ~/.bashrc
      echo "********************************************"
      cat ~/.bash
      source /etc/environment
      echo $JAVA_HOME
      echo "Running script from Azure Pipelines"
      echo $PATH
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    jdkDirectory: '/etc/aazeemxyz/java'
    #javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.10'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'
