
# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  ARSHAD_KEY: ARSHAD_VAL
  JAVA_HOME: /usr/aazeem
steps:
- task: CmdLine@2
  inputs:
    env:
      a=b
    script:
      echo "Setting up JAVA_HOME..."
      echo "********************************************"
      echo $JAVA_HOME
      echo $ARSHAD_KEY
      echo "Running script from Azure Pipelines"
      export PATH=$ARSHAD_KEY/binzz:$PATH
      echo $PATH
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    jdkDirectory: $JAVA_HOME
    #javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.10'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'
